[package]
name = "resmap"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/stackinspector/resmap"

[[bin]]
name = "resmap"
path = "main.rs"

[dependencies]
crc32fast = "1"
hex = "0.4"
